export const FETCH_COURSES = "FETCH_COURSES"

export const FETCH_COURSE = "FETCH_COURSE"

export const FETCH_QUIZZES = "FETCH_QUIZZES"

export const FETCH_QUIZ = "FETCH_QUIZ"

export const FETCH_QUESTIONS = "FETCH_QUESTIONS"

export const SELECT_QUESTION = "SELECT_QUESTION"

export const GET_EXAM = "GET_EXAM"

export const USER_LOGIN = "USER_LOGIN"

export const ADD_QUESTION_FORUM = "ADD_QUESTION_FORUM"